APP:
    ENVIRONMENT: test
    local_path : '/home/jonay/Projects/calidadAire/calidad_aire/Files/'
    url : 'https://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=aecb88a7e2b73410VgnVCM2000000c205a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD&vgnextfmt=default'
    domain : 'https://datos.madrid.es'
    